#
# Travis CI configuration for testing codeception-module-http-auth
#

language: php
php:
  - 5.4

before_script:
  # Copy testing.composer.json to a new directory and run composer install.
  - mkdir http-auth-testing
  - cp ./tests/testing.composer.json ./http-auth-testing/composer.json
  - composer install -d http-auth-testing
  - cd http-auth-testing
  - vendor/bin/codecept build -c vendor/pfaocle/codeception-module-http-auth/codeception.yml

# Run tests in codeception-module-http-auth project with Codeception install set up above.
script:
  - vendor/bin/codecept run -c vendor/pfaocle/codeception-module-http-auth/codeception.yml acceptance
  - vendor/bin/codecept run -c vendor/pfaocle/codeception-module-http-auth/codeception.yml acceptance-misconfigured
